name: CI

on:
    push:
        branches: [ "**" ]
    pull_request:
        branches: [main]

jobs:
    dbt_test:
        name: "Run on Push"
        runs-on: ubuntu-latest
        environment: development
        env:
            SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true
            SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
            SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
            SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
            SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA_DEV }}
            SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
            SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Set up virtual environment
              run: python -m venv .venv
            - name: Activate virtual environment
              run: source .venv/bin/activate
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install dbt-snowflake
            - name: Debug connection
              run: cd dbt_project && dbt debug --target dev
            - name: Run dbt models
              run: cd dbt_project && dbt run --target dev
            - name: Run dbt tests
              run: cd dbt_project && dbt test --target dev
